package com.example.tp1

object PersonDescription {
    private val descriptions = mutableMapOf(
        "Linus Torvalds" to Pair("Né le 28 décembre 1969 à Helsinki en Finlande, est un informaticien connu pour avoir créer le noyau Linux", "Linus Benedict Torvalds, né le 28 décembre 1969 à Helsinki en Finlande, est un informaticien américano-finlandais2,3 connu notamment pour avoir créé le noyau Linux en 1991 (à 21 ans)." +
                "                \"Il continue d'en diriger le développement, étant considéré comme le « dictateur bienveillant à vie » (Benevolent Dictator for Life) de celui-ci. Il a également créé le logiciel de gestion de versions décentralisée Git et le logiciel d'enregistrement et de planification des plongées Subsurface (en)." +
                "                \"En 2012, il reçoit le prix Millennium Technology, décerné par la Technology Academy Finland (en) pour son travail sur Linux. Il est également lauréat en 2014 du Computer Pioneer Award, décerné par l'IEEE Computer Society. Linus Torvalds fait partie de la communauté des Finlandais suédophones (Finlandssvensk), une population représentant 6 % des habitants de la Finlande. Son père, Nils Torvalds, est journaliste de télévision et de radio et aussi membre actif du Parti populaire suédois (le parti des suédophones finlandais), élu député européen en 2012. Sa mère, Anna, est également journaliste4,5, et il compte parmi ses grands-parents le statisticien Leo Törnqvist6 et le poète Ole Torvalds7." +
                "                \"Le prénom de Linus lui vient de Linus Pauling, chimiste américain récipiendaire du prix Nobel, mais Torvalds lui-même explique qu’il « pense avoir aussi été nommé d’après Linus, le personnage des Peanuts », ce qui le rend « à moitié chimiste nobélisé et à moitié personnage de BD portant une couverture »8. \" +\n" +
                "                \"Il découvre l'informatique vers l’âge de 11 ans grâce à l'ordinateur de son grand-père, un Commodore VIC-209."),
        "Richard Stallman" to Pair("Né le 16 mars 1953 est un programmeur et militant du logiciel libre.", "Richard Matthew Stallman, né le 16 mars 1953 à Manhattan, connu aussi sous les initiales rms (en minusculesn 1), est un programmeur et militant du logiciel libre. Initiateur du mouvement du logiciel libre, il lance, en 1983, le projet GNU et la licence publique générale GNU connue aussi sous le sigle GPL. Il a popularisé le terme anglais « copyleft »n 2. Programmeur renommé de la communauté informatique américaine et internationale, il a développé de nombreux logiciels dont les plus connus des développeurs sont l’éditeur de texte GNU Emacs, le compilateur C de GNU (GCC), le débogueur GNU (gdb) mais aussi, en collaboration avec Roland McGrath, le moteur de production GNU Make." +
                "                \"Depuis le milieu des années 1990, il consacre la majeure partie de son temps à la promotion des logiciels libres auprès de divers publics un peu partout dans le monde. Depuis quelques années, il fait campagne contre les brevets logiciels et la gestion des droits numériques (DRM)1. Le temps qu’il alloue encore à la programmation est consacré à GNU Emacs, bien qu’il ne soit plus le mainteneur principal depuis février 2008. Il gagne sa vie en partie avec les cachets de conférencier qu’on lui donne à l’occasion ou des prix qu’on lui remet. \" +\n" +
                "                \"En 2010, un récit biographique qui relate la vie de Richard Stallman paraît en français sous le titre Richard Stallman et la révolution du logiciel libre."),
        "John McCarthy" to Pair("Né le 3 septembre 1927 est le principal pionnier de l'intelligence artificielle.", "John McCarthy, né le 3 septembre 1927, à Boston (Massachusetts) et mort le 24 octobre 2011 à Stanford (Californie)2, est le principal pionnier de l'intelligence artificielle avec Marvin Lee Minsky ; il incarne le courant mettant l'accent sur la logique symbolique. \" +\n" +
                "                \"À la fin des années 1950, après un doctorat en mathématiques, il a créé avec Fernando Corbató la technique du temps partagé, qui permet à plusieurs utilisateurs d'employer simultanément un même ordinateur. Il est également le créateur du langage LISP, en 1958. Il reçoit le prix Turing en 1971 pour ses travaux en intelligence artificielle. En 1956, il préside la conférence de Dartmouth, lors de laquelle il présente le principe d'élagage alpha-bêta, un algorithme d'évaluation jouant un rôle majeur dans la programmation en intelligence artificielle, notamment utilisé par la grande majorité des programmes d'échecs. Vers les années 1960, le programme Kotok-McCarthy, dont il est à l'origine, est l'un des plus performants. Il est également l'inventeur en 1958 du langage Lisp2. Il quitte le MIT en 1962 pour créer le laboratoire d'intelligence artificielle de l'université Stanford. À partir de 1962, McCarthy est professeur à l'université Stanford, jusqu'à ce qu'il prenne sa retraite en 2000. Il est aussi l'un des pionniers du cloud computing 5. Il reçoit le prix Turing en 1971 pour ses travaux en intelligence artificielle. \" +\n" +
                "                \"Pendant sa retraite, il écrit une nouvelle de science-fiction, intitulée Le Robot et le bébé6, « pour illustrer en partie ce que les robots domestiques devraient être »7."),
        "Andy Gavin" to Pair("Né le 11 juin 1970 est un programmeur de jeux vidéo.", "Andrew Scott Gavin (born June 11, 1970) is an American video game programmer, entrepreneur, and novelist. Gavin co-founded the video game company Naughty Dog with childhood friend Jason Rubin in 1986, which released games including Crash Bandicoot and Jak & Daxter.[1] Prior to founding Naughty Dog, Gavin worked in LISP at the MIT Artificial Intelligence Laboratory. Gavin and Rubin sold their first video game, Math Jam, in 1985. In 1989, they sold Keef the Thief to Electronic Arts.[5] In the early 1990s, their fighting game, Way of the Warrior, led to a multi-title deal with Universal Interactive Studios.[6] Under the auspices of this Universal deal they produced the Crash Bandicoot series from 1994 until 1999, and later the Jak and Daxter series. At the end of 2000, Rubin and Gavin sold Naughty Dog to Sony Computer Entertainment America (SCEA), having released 14 Naughty Dog games, which together sold over 35 million units and generated over 1 billion in revenue. \" +\n" +
                "                \"While at Naughty Dog, Gavin developed two LISP dialects for use in game development, Game Object Oriented Lisp (GOOL) and its successor Game Oriented Assembly Lisp (GOAL). These included innovations in terms of language choice and design. \" +\n" +
                "                \"Shortly after leaving Naughty Dog in 2004, Gavin and Rubin co-founded a new Internet startup called Flektor with former HBO executive Jason R. Kay. In May 2007, the company was sold to Fox Interactive Media, a division of News Corp.[9] Fox described the company as \\\"a next-generation Web site that provides users with a suite of Web-based tools to transform their photos and videos into dynamic slideshows, postcards, live interactive presentations, and video mash-ups.\\\" In October 2007, Flektor partnered sister company MySpace, and MTV to provide instant audience feedback via polls for the interactive MySpace / MTV Presidential Dialogues series with Senator and presidential candidate Barack Obama. " +
                "                \"Gavin left Fox Interactive Media in 2008. In 2009, he and Rubin announced a new social game startup called Monkey Gods, which was working on a new version of Snood along with a casual word game called MonkWerks. \" +\n" +
                "                \"Gavin also released a dark historical fantasy novel, The Darkening Dream, published in December 2011.[12] His second novel Untimed, which involves time travel, was released on December 19, 2012."),
        "Brian Kernighan" to Pair("Né le 30 janvier 1942 est un informaticien canadien.", "Brian Kernighan ˈkɛrnɪhæn (né le 1er janvier 1942 à Toronto, Canada) est un informaticien connu pour avoir coécrit le premier livre sur le langage de programmation C (avec Dennis Ritchie). Il est aussi le cocréateur des langages Awk, avec Alfred Aho et Peter Weinberger, et AMPL. \" +\n" +
                "                \"En 1969, il obtient un doctorat d'électrotechnique à l'université de Princeton1, où en 2004, il occupe un poste de professeur. \" +\n" +
                "                \"En collaboration avec Lin Shen, il imagina les heuristiques bien connues pour deux problèmes d'optimisation NP-complet : partitionnement de graphe et le problème du voyageur de commerce (le premier est habituellement appelé algorithme de Kernighan-Lin, et le second est Lin-Kernighan). \" +\n" +
                "                \"Kernighan est également connu comme à l'origine de l'expression « What you see is all you get » (WYSIAYG), (littéralement « Vous n'avez que ce que vous voyez ») une variante ironique de « What you see is what you get » (WYSIWYG) (littéralement « Ce que vous voyez est ce que vous obtenez »). L'expression de Kernighan sous-entend que les systèmes WYSIWYG risquent de faire perdre à un document des informations potentiellement utiles en ne restituant que ce qui est visible. \" +\n" +
                "                \"Il a révélé à l'occasion, que c'est son propre jeu de mots qui a conduit à l'utilisation du nom « Unix » (initialement Unics') pour le système d'exploitation de Ken Thompson et Dennis Ritchie."),
        "Dennis Ritchie" to Pair("Né le 9 septembre 1941 est l'inventeur du language C et codéveloppeur de Unix.", "Dennis MacAlistair Ritchie, né le 9 septembre 1941 à Bronxville dans l'État de New York et retrouvé mort le 12 octobre 20111 à Berkeley Heights dans le New Jersey, est un des pionniers de l'informatique moderne, inventeur du langage C et codéveloppeur de Unix. Il est parfois désigné par dmr, son adresse électronique aux Laboratoires Bell. \" +\n" +
                "                \"Au début des années 1970, programmeur aux Laboratoires Bell, il travaille avec Ken Thompson au développement d'Unix. Le langage B de Thompson étant trop limité pour les besoins du nouveau système, Ritchie est amené à créer sur les mêmes bases le langage C. Par la suite, avec l'aide de Brian Kernighan, il promeut le langage et rédige notamment le livre de référence The C Programming Language. \" +\n" +
                "                \"Il reçoit conjointement avec Ken Thompson le prix Turing de l'ACM en 1983 pour leur travail sur le système Unix. Dennis Ritchie nait en 1941 à Bronxville dans l'État de New York. Son père, Alistair E. Ritchie, est un scientifique des Laboratoires Bell et connu pour le livre The Design of Switching Circuits sur la théorie des commutation de circuits, dont il est co-auteur. Dennis Ritchie étudie la physique ainsi que les mathématiques appliquées à Harvard, y obtenant un doctorat. \" +\n" +
                "                \"En 1967, il commence à travailler également aux Laboratoires Bell, où son père fait lui-même carrière. Un an plus tard, en 1968, il soutient sa thèse, nommée Program Structure and Computational Complexity, à Harvard sous la supervision de Patrick C. Fischer. Cependant, disposant déjà d'un poste chez Bell Labs, Ritchie n'a jamais pris le temps de remettre sa thèse sous forme de volume relié à l'université de Harvard, créant ainsi une difficulté administrative qui empêcha l'université de lui décerner officiellement son doctorat. Celle-ci a depuis été redécouverte auprès de la veuve de son directeur de thèse, et republiée en ligne. \" +\n" +
                "                \"En 1978, Ritchie co-écrit avec Brian Kernighan The C programming language, un livre sur le langage C. C'est l'une de ses contributions les plus célèbres, puisque le livre est encore aujourd'hui connu sous le nom de K&R, les initiales des deux auteurs. \" +\n" +
                "                \"Ritchie travaille également dans les années suivantes avec Ken Thompson sur le système d'exploitation UNIX. Ritchie est notamment le contributeur principal du portage d'UNIX sur différentes machines et plateformes. \" +\n" +
                "                \"En 1983, Ritchie et Thompson reçoivent le prix Turing pour leurs travaux sur la théorie d'un système d'exploitation générique et l'implémentation du modèle sur le système UNIX. Le prix de Ritchie est par ailleurs intitulé « Reflections on Software Research ». En 1990, Ritchie et Thompson seront de nouveaux récompensés, par la médaille Richard W. Hamming de l'IEEE pour le système UNIX et le langage C. \" +\n" +
                "                \"Le 21 avril 1999, Thompson et Ritchie reçoivent la National Medal of Technology and Innovation de 1998, par le président américain Bill Clinton, toujours pour l'invention d'UNIX et du langage C. Ces inventions ont, d'après le jury, « permis d'énormes avancées dans l'informatique matérielle et logicielle et les réseaux et a stimulé la croissance de toute l'industrie, confortant le leadership des États-Unis dans le domaine des systèmes d'information ». \" +\n" +
                "                \"De santé précaire, après le traitement d'un cancer de la prostate et de problèmes cardiaques10, il meurt à l'âge de 70 ans à son domicile de Berkeley Heights dans l’État du New Jersey où, vivant seul, il est retrouvé le mercredi 12 octobre 2011, inerte10. La date de sa mort n'est pas connue avec certitude, mais pourrait se situer autour du 8 ou 9 octobre, selon les sources inspirées par les proches11,12,13,14. Son décès est occulté par celui de Steve Jobs, survenu quelques jours auparavant, bien que Mac OS et iOS se basent sur les travaux de Dennis Ritchie effectués sur UNIX. "),
        "Ken Thompson" to Pair("Né le 4 février 1943 est un informaticien américain, concepteur des systèmes Unix et Plan 9.", "Kenneth Lane Thompson dit Ken Thompson (né le 4 février 1943 à La Nouvelle-Orléans) est un informaticien américain, concepteur des systèmes Unix et Plan 9 ainsi que des langages B et Go. Après avoir obtenu ses diplômes à l'université de Californie à Berkeley, il rejoint les Laboratoires Bell en 19662. Il y travaille sur les systèmes d'exploitation à temps partagé, notamment Multics, puis Unix à partir de 1969 et plus tard Plan 9. En 1970, il met au point le langage B, précurseur du C. \" +\n" +
                "                \"Il participe à de nombreuses évolutions du système Unix : portage sur PDP-11, réécriture en langage C, et introduction des pipes. \" +\n" +
                "                \"Dans les années 1970, il crée Belle3 avec Joseph Condon, un ordinateur spécialisé dans le jeu d'échecs. Belle remporte à plusieurs reprises le championnat nord-américain des ordinateurs d'échecs entre 1978 et 1986. Il est également à l'origine des recherches sur les tables de finales4. \" +\n" +
                "                \"En 1979, AT&T publie dbm, un moteur de base de données qu'il a initié. \" +\n" +
                "                \"Il est également l'inventeur de l'éditeur ed et avec Rob Pike du codage des caractères UTF-8. \" +\n" +
                "                \"Il reçoit conjointement avec Dennis Ritchie le prix Turing de l'ACM en 1983, et la médaille nationale de la technologie des États-Unis en 1998 pour leur travail sur le système Unix. À la réception du prix il donne une conférence qui met en garde contre les chevaux de Troie5. \" +\n" +
                "                \"Il a pris sa retraite des Bell Labs en 20006. Il a travaillé à Entrisphere comme conseiller scientifique jusqu'en 2006 et travaille désormais chez Google. \" +\n" +
                "                \"C'est chez Google qu'il participe à la création d'un nouveau langage de programmation, issu du C et appelé Go : « Chez Google, nous pensons que la programmation devrait être rapide, productive et surtout, « fun ». C’est pourquoi nous sommes ravis de proposer ce nouveau langage de programmation expérimental. Les opérations de compilation sont presque instantanées, et le code compilé propose une vitesse de fonctionnement proche de celle du C7. » \" +\n" +
                "                \"En 2011, il est corécipiendaire avec Dennis Ritchie du prix japonais."),
        "Steve Wozniak" to Pair("Né le 11 août 1950 est un informaticien, inventeur, professeur et électronicien.", "Stephen Wozniak, dit Steve Wozniak, né le 11 août 1950 à San José, aussi appelé Woz, est un informaticien, inventeur, professeur d'informatique et électronicien américain. \" +\n" +
                "                \"Il est cofondateur de la société Apple Computer avec Steve Jobs et Ronald Wayne, et concepteur des premiers Apple (dont Apple I, Apple II, Apple III, Lisa et divers périphériques), et est un des pionniers de l'industrie micro-informatique. Steve Wozniak fait la connaissance de Steve Jobs en 1970 grâce à son voisin Bill Fernandez, alors camarade de classe de Jobs à la Homestead High School. Partageant la même passion de l'électronique, ils deviennent amis et réalisent ensemble de nombreux canulars. En octobre 1971, les deux Steve mettent la main sur un article du magazine Esquire qui explique comment fabriquer une blue box, un appareil qui permet de passer des appels longue distance de façon entièrement gratuite en fraudant les compagnies téléphoniques, et plus précisément AT&T. Ils décident alors d'en fabriquer et de les vendre pour 150 \\\$ l'unité, pour un total de 200 exemplaires environ. Selon Steve Jobs, cette expérience est à l'origine d'Apple. \" +\n" +
                "                \"En février 1973, Wozniak est embauché par Hewlett-Packard dans le département des produits avancés qui produit des calculatrices, où il est rapidement rejoint par Bill Fernandez. Il tente alors de rejoindre la division ordinateur de HP, en vain. Steve Jobs est employé par Atari pour développer des jeux vidéo, tâche dans laquelle il est aidé par Wozniak pendant son temps libre. \" +\n" +
                "                \"\\n\" +\n" +
                "                \"Apple I de Steve Wozniak et Steve Jobs. \" +\n" +
                "                \"Micromodem II dans l'Apple II. \" +\n" +
                "                \"Dans son autobiographie iWoz, il rapporte que c'est Steve Jobs qui eut l’idée de vendre un ordinateur sous la forme d'un circuit imprimé préassemblé. Bien que sceptique en premier lieu, par la suite Wozniak est convaincu par Jobs que, même si cela est un échec, ils pourront toujours raconter à leurs petits enfants qu'ils avaient eu leur propre société. Pour rassembler des fonds, Wozniak vend sa calculatrice programmable HP-65, Jobs son Volkswagen Combi, les deux en obtenant 1 750 \\\$, ce qui leur servira pour assembler leur prototype. \" +\n" +
                "                \"Sur la base d'un processeur MOS Technology 6502 qu'il découvre en septembre 1975, Wozniak écrit un interpréteur BASIC émulé sur une machine HP. Le circuit de cette machine, l’Apple I, est entièrement conçu par Steve Wozniak ; bien que sommaire, il impressionne les membres du Homebrew Computer Club, un club de Palo Alto réunissant des passionnés d'informatique. Contrairement à d'autres machines admirées par le groupe comme l'Altair 8800, l'Apple I est capable d'affichage graphique sur un écran. Le travail commence dans la chambre de Jobs à Los Altos puis, lorsque la pièce devient trop exiguë, ils transfèrent leur atelier de montage dans le garage de la famille Jobs. L’appartement de Wozniak à San José est lui rempli de moniteurs, d'appareils électroniques et de quelques jeux vidéo développés par Wozniak. \" +\n" +
                "                \"Le 1er avril 1976, Jobs et Wozniak forment leur société, Apple Computer. Wozniak quitte son travail chez Hewlett-Packard au mois de mai 1976 et devient vice-président d'Apple, responsable de la recherche et du développement. Jobs et Wozniak placent leurs 50 premiers ordinateurs au magasin « Byte Shop », un revendeur local, pour 25 000 \\\$, soit 500 \\\$ pièce, et revendu 666,66 \\\$. Fin 1976, grâce à un investissement de 92 000 \\\$ de Mike Markkula, la société Apple engrange près d'un million de dollars avec de nouvelles ventes. \" +\n" +
                "                \"Wozniak se concentre alors à plein temps à l'amélioration de l'Apple I et lui ajoute de nouvelles fonctionnalités. Sa nouvelle machine doit conserver les caractéristiques les plus importantes de l'Apple I : simplicité et rentabilité. Wozniak ajoute le graphisme haute résolution à l'Apple II, qui peut maintenant afficher des images aussi bien que des lettres. \" +\n" +
                "                \"\\n\" +\n" +
                "                \"Steve Wozniak en 1983. \" +\n" +
                "                \"En 1978, il conçoit un lecteur de disquette peu coûteux ; Randy Wigginton et lui écrivent un système d'exploitation de base. En plus de son don pour le matériel, Wozniak écrit la majeure partie des logiciels qui tournent sur l'Apple II. Il programme un interpréteur BASIC, un jeu de casse-briques (qui est l'occasion d'ajouter du son à la machine), le code pour commander le lecteur de disquettes, et plus encore. Côté logiciel, l'Apple II est également rendu plus attrayant pour un utilisateur professionnel par l'apparition du fameux tableur VisiCalc de Dan Bricklin et Bob Frankston. Le 12 décembre 1980, La société Apple entre en bourse et fait de Jobs et Wozniak des millionnaires, avec respectivement 7,8 et 4 millions d'actions chacun, introduites à 22 \\\$. \" +\n" +
                "                \"Ses travaux pour Apple cessent après un accident d'avion en février 1981, à la suite duquel il souffre d'amnésies pendant quelques semaines et devient moins enthousiaste dans son travail pour Apple. Il se marie avec Candice Clark, retourne à l'université sous le nom de « Rocky Clark » pour obtenir en 1986 ses diplômes en informatique et en électrotechnique. \" +\n" +
                "                \"En 1983, il revient chez Apple d'une manière assez originale : il rentre dans l'un des bâtiments de l'unité Apple et demande tout simplement s'il peut faire quelque chose. Il découvre alors le projet Apple IIgs, avec son microprocesseur 65816. \" +\n" +
                "                \"Cependant, à cause de problèmes externes et internes, il quitte Apple le 6 février 1987, 12 ans après la création de la société ; il touche d'Apple un salaire symbolique d'environ 120 000 \\\$ par an. Steve Jobs quitte ensuite Apple à la suite d'une lutte de pouvoir à la tête de la société. Wozniak sponsorise alors des actions caritatives dans le domaine de l'éducation, ce qui ne l'empêche pas d'acheter les nouveaux produits Apple afin de les étudier et les mettre à la disposition des écoles."),
        "Bjarne Stroustrup" to Pair("Né le 30 décembre 1950 est un informaticien, écrivain et professeur de sciences informatiques.", "Bjarne Stroustrup (/ˈbjaːnə ˈstʁʌwˀstʁɔp/2), né le 30 décembre 1950 à Aarhus, est un informaticien, écrivain et professeur de sciences informatiques danois. Il est connu pour être l'auteur du langage de programmation C++, l'un des plus utilisés dans le monde.\n" +
                "Stroustrup obtient une maîtrise en mathématiques et en sciences informatiques à l'université d'Aarhus en 1975. Il prépare ensuite un doctorat en informatique à l'université de Cambridge en Angleterre, qu'il obtient en 1979. Il part alors vivre dans le New Jersey aux États-Unis, où il travaille pour les laboratoires Bell jusqu'en 2002. Après avoir été professeur à l'université A&M du Texas aux États-Unis, où il était titulaire de la chaire de science informatique du collège d'ingénierie jusqu'en janvier 2014, il est maintenant administrateur délégué chez Morgan Stanley à New York3. Il est fellow de l'ACM (1994) et de l'IEEE."),
        "Tim Sweeney" to Pair("Né en 1970, fondateur d'Epic Games.", "Sweeney a fréquenté l'Université du Maryland à partir de 1989 environ, où il a étudié le génie mécanique[2], bien qu'il soit toujours fasciné par les ordinateurs.[6] À cette époque, son père, qui travaillait pour la Defense Mapping Agency, lui a donné un IBM Personal Computer/AT.[6] Sweeney a créé une entreprise de conseil, Potomac Computer Systems, hors de la maison de ses parents pour offrir de l'aide avec les ordinateurs, mais cela n'a jamais décollé et il a mis l'entreprise en veilleuse. Plus tard, Sweeney a eu l'idée de créer des jeux qui pourraient être vendus, en les programmant la nuit ou le week-end en dehors du travail universitaire. Cela l'a d'abord obligé à créer un éditeur de texte basé sur le langage Pascal pour pouvoir programmer le jeu, ce qui a conduit à l'idée de faire un jeu à partir de l'éditeur de texte lui-même. Cela est devenu la base de ZZT. Il a laissé des amis de l'université et ceux de son voisinage donner leur avis, et était conscient que c'était quelque chose qu'il pouvait vendre à d'autres utilisateurs d'ordinateurs. Pour distribuer le jeu, Sweeney s'est tourné vers le modèle du shareware et a écrit à Scott Miller d'Apogee Software, Ltd., l'un des principaux producteurs de shareware à l'époque, pour avoir des idées sur la façon de distribuer ZZT. Il a revitalisé Potomac Computer Systems pour la vente de ZZT, remplissant les commandes par correspondance avec l'aide de son père. ZZT s'est vendu suffisamment bien, quelques exemplaires par jour pour environ 100 dollars par jour, pour que Sweeney décide de faire du développement de jeux sa carrière. Reconnaissant qu'il avait besoin d'un meilleur nom pour une société de jeux vidéo, il a renommé Potomac Computer Systems en Epic MegaGames.[2] \" +\n" +
                "                \"\\n\" +\n" +
                "                \"Sweeney fait une présentation à la Game Developers Conference 2016 \" +\n" +
                "                \"Après ZZT, Sweeney a commencé à travailler sur son prochain titre, Jill of the Jungle, mais a constaté qu'il n'avait pas les compétences nécessaires pour le terminer seul. Il a formé une équipe de quatre personnes pour terminer le jeu à la mi-1992.[6] Pour un développement continu, Sweeney a recherché un partenaire commercial pour Epic MegaGames, venant finalement à Mark Rein, qui venait d'être licencié d'id Software. Rein a aidé à développer et à gérer l'entreprise; en raison de la croissance de l'entreprise, Sweeney n'a pas fini par obtenir son diplôme, à court d'un crédit.[2] Sweeney commencera plus tard à travailler sur l'Unreal Engine, développé pour le jeu de tir à la première personne Unreal de 1998 et autorisé par plusieurs autres jeux vidéo.[6][7] Avec le succès d'Unreal, la société a déménagé en Caroline du Nord en 1999 et a changé son nom pour Epic Games.[8]"),
        "Tim Berners-Lee" to Pair("Né le 8 juin 1955 est le principal inventeur du World Wide Web", "Timothy John Berners-Lee, né le 8 juin 1955 à Londres, est un informaticien britannique, principal inventeur du World Wide Web (WWW, le Web) alors qu'il travaillait au CERN au tournant des années 1990. Depuis 1994, il préside le World Wide Web Consortium (W3C), organisme qu'il a fondé. En juillet 2004, il est fait chevalier par la reine Élisabeth II. Il est lauréat du prix Turing 20161. \" +\n" +
                "                \"En créant le Web, Tim Berners-Lee invente ses trois technologies fondatrices : les adresses Web sous forme d'URL, le protocole de communication HTTP, et le langage informatique HTML. Il fut aidé à ses débuts par l'ingénieur et informaticien belge Robert Cailliau qui cosigna notamment avec lui, en novembre 1990, un document désormais entré dans l'Histoire et intitulé « WorldWideWeb : Proposition pour un projet hypertexte2». Tim Berners-Lee a vu le jour le 8 juin 1955 à Londres, en Angleterre3. Fils de Conway Berners-Lee et de Mary Lee Woods, il étudie la physique au Queen's College de l'Université d'Oxford de 1973 à 1976, année durant laquelle il obtient une maîtrise en physique4. Il profite de ses années à l'Université d'Oxford pour fabriquer son premier ordinateur à partir d'un microprocesseur Motorola 6800 et d'une vieille télévision. \" +\n" +
                "                \"Après l'obtention de sa maîtrise, il travaille pour Plessey Telecommunications Ltd5, fabricant d’équipements de télécommunications, puis pour D. G. Nash Ltd5, une entreprise spécialisée dans l’impression informatique4. \" +\n" +
                "                \"Tim Berners-Lee est père de deux enfants."),
        "John von Neumann" to Pair("Né le 28 décembre 1903 est un mathématicien et physicien.", "John von Neumann (János Lajos Neumann) (ˈnojmɒn ˈjaːnoʃ ˈlɒjoʃ, János Lajos Neumann en hongrois), né le 28 décembre 1903 à Budapest et mort le 8 février 1957 à Washington, est un mathématicien et physicien américano-hongrois. Il a apporté d'importantes contributions en mécanique quantique, en analyse fonctionnelle, en logique mathématique, en informatique théorique, en sciences économiques et dans beaucoup d'autres domaines des mathématiques et de la physique. Il a de plus participé aux programmes militaires américains. C'est âgé d'à peine 22 ans qu'il reçoit son doctorat en mathématiques (et en physique expérimentale et en chimie comme matières secondaires) de l'université de Budapest pour une thèse sur l'axiomatisation de la théorie des ensembles3. En parallèle, il obtient un diplôme en génie chimique de l'École polytechnique fédérale de Zurich (à la demande de son père, désireux que son fils s'investisse dans un secteur plus rémunérateur que les mathématiques4), et aussi sur les conseils de Theodore von Kármán. Neumann ne fréquente ces deux universités que pour passer les examens. Il est le major de sa promotion pour les deux universités. \" +\n" +
                "                \"Entre 1926 et 1930, il est le plus jeune au monde5 à recevoir à 25 ans le titre de privatdozent à Berlin et à Hambourg. Il reçoit une bourse de la fondation Rockefeller pour travailler également à l'université de Göttingen — à l'époque capitale mondiale des mathématiques et de la physique théorique — avec Robert Oppenheimer sous la direction de David Hilbert6. Durant cette « période allemande », l'une des plus fécondes de sa vie, il côtoie également Werner Heisenberg et Kurt Gödel.")

    )

    fun getDescriptionShort(name: String): String? {
        return descriptions[name]?.first
    }

    fun getDescriptionLong(name: String): String? {
        return descriptions[name]?.second
    }

    fun setDescription(name: String, shortDescription: String, longDescription: String) {
        descriptions[name] = Pair(shortDescription, longDescription)
    }


}